name: "Setup Node.js and pnpm"
description: "Sets up Node.js, pnpm, caches dependencies, and installs them"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
        cache: "pnpm"

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
